// Données statiques des matières pour le rendu initial (avant Supabase)
export interface SubjectData {
  name: string
  slug: string
  category: 'tronc_commun' | 'specialite'
  icon: string // Lucide icon name
  color: string
  description: string
  level: 'premiere' | 'terminale' | 'both'
  sort_order: number
}

export const subjectsData: SubjectData[] = [
  // Spécialités
  {
    name: 'Mathématiques',
    slug: 'mathematiques',
    category: 'specialite',
    icon: 'ruler',
    color: '#3B82F6',
    description: 'Annales et exercices corrigés de Maths spécialité',
    level: 'both',
    sort_order: 1,
  },
  {
    name: 'Physique-Chimie',
    slug: 'physique-chimie',
    category: 'specialite',
    icon: 'flask-conical',
    color: '#8B5CF6',
    description: 'Annales et exercices corrigés de Physique-Chimie',
    level: 'both',
    sort_order: 2,
  },
  {
    name: 'SVT',
    slug: 'svt',
    category: 'specialite',
    icon: 'dna',
    color: '#10B981',
    description: 'Annales et exercices corrigés de SVT',
    level: 'both',
    sort_order: 3,
  },
  {
    name: 'SES',
    slug: 'ses',
    category: 'specialite',
    icon: 'bar-chart-3',
    color: '#F59E0B',
    description: 'Annales et exercices corrigés de SES',
    level: 'both',
    sort_order: 4,
  },
  {
    name: 'HGGSP',
    slug: 'hggsp',
    category: 'specialite',
    icon: 'globe',
    color: '#EF4444',
    description: 'Histoire-Géo, Géopolitique et Sciences Politiques',
    level: 'both',
    sort_order: 5,
  },
  {
    name: 'NSI',
    slug: 'nsi',
    category: 'specialite',
    icon: 'monitor',
    color: '#06B6D4',
    description: 'Numérique et Sciences Informatiques',
    level: 'both',
    sort_order: 6,
  },
  {
    name: 'LLCE Anglais',
    slug: 'llce-anglais',
    category: 'specialite',
    icon: 'languages',
    color: '#EC4899',
    description: 'Langues, Littératures et Cultures Étrangères',
    level: 'both',
    sort_order: 7,
  },
  {
    name: 'HLP',
    slug: 'hlp',
    category: 'specialite',
    icon: 'library',
    color: '#78716C',
    description: 'Humanités, Littérature et Philosophie',
    level: 'both',
    sort_order: 8,
  },
  {
    name: 'Sciences de l\'Ingénieur',
    slug: 'sciences-ingenieur',
    category: 'specialite',
    icon: 'settings',
    color: '#64748B',
    description: 'Annales et exercices corrigés de SI',
    level: 'both',
    sort_order: 9,
  },
  // Tronc commun
  {
    name: 'Français',
    slug: 'francais',
    category: 'tronc_commun',
    icon: 'pen-tool',
    color: '#7C3AED',
    description: 'Épreuves anticipées de Français (écrit + oral)',
    level: 'premiere',
    sort_order: 10,
  },
  {
    name: 'Philosophie',
    slug: 'philosophie',
    category: 'tronc_commun',
    icon: 'lightbulb',
    color: '#B45309',
    description: 'Annales et sujets corrigés de Philo',
    level: 'terminale',
    sort_order: 11,
  },
  {
    name: 'Histoire-Géographie',
    slug: 'histoire-geographie',
    category: 'tronc_commun',
    icon: 'map',
    color: '#DC2626',
    description: 'Tronc commun Histoire-Géographie',
    level: 'both',
    sort_order: 12,
  },
  {
    name: 'Enseignement Scientifique',
    slug: 'enseignement-scientifique',
    category: 'tronc_commun',
    icon: 'microscope',
    color: '#059669',
    description: 'Enseignement Scientifique tronc commun',
    level: 'both',
    sort_order: 13,
  },
  {
    name: 'Anglais',
    slug: 'anglais',
    category: 'tronc_commun',
    icon: 'message-circle',
    color: '#2563EB',
    description: 'Épreuves d\'anglais tronc commun',
    level: 'both',
    sort_order: 14,
  },
  {
    name: 'Grand Oral',
    slug: 'grand-oral',
    category: 'tronc_commun',
    icon: 'mic',
    color: '#D97706',
    description: 'Préparation au Grand Oral du Bac',
    level: 'terminale',
    sort_order: 15,
  },
]
