// Données statiques des matières pour le rendu initial (avant Supabase)
interface SubjectData {
  name: string
  slug: string
  category: 'tronc_commun' | 'specialite'
  icon: string
  color: string
  description: string
  level: 'premiere' | 'terminale' | 'both'
  sort_order: number
}

export const subjectsData: SubjectData[] = [
  // Spécialités
  {
    name: 'Mathématiques',
    slug: 'mathematiques',
    category: 'specialite' as const,
    icon: '📐',
    color: '#3B82F6',
    description: 'Annales et exercices corrigés de Maths spécialité',
    level: 'both' as const,
    sort_order: 1,
  },
  {
    name: 'Physique-Chimie',
    slug: 'physique-chimie',
    category: 'specialite' as const,
    icon: '⚗️',
    color: '#8B5CF6',
    description: 'Annales et exercices corrigés de Physique-Chimie',
    level: 'both' as const,
    sort_order: 2,
  },
  {
    name: 'SVT',
    slug: 'svt',
    category: 'specialite' as const,
    icon: '🧬',
    color: '#10B981',
    description: 'Annales et exercices corrigés de SVT',
    level: 'both' as const,
    sort_order: 3,
  },
  {
    name: 'SES',
    slug: 'ses',
    category: 'specialite' as const,
    icon: '📊',
    color: '#F59E0B',
    description: 'Annales et exercices corrigés de SES',
    level: 'both' as const,
    sort_order: 4,
  },
  {
    name: 'HGGSP',
    slug: 'hggsp',
    category: 'specialite' as const,
    icon: '🌍',
    color: '#EF4444',
    description: 'Histoire-Géo, Géopolitique et Sciences Politiques',
    level: 'both' as const,
    sort_order: 5,
  },
  {
    name: 'NSI',
    slug: 'nsi',
    category: 'specialite' as const,
    icon: '💻',
    color: '#06B6D4',
    description: 'Numérique et Sciences Informatiques',
    level: 'both' as const,
    sort_order: 6,
  },
  {
    name: 'LLCE Anglais',
    slug: 'llce-anglais',
    category: 'specialite' as const,
    icon: '🇬🇧',
    color: '#EC4899',
    description: 'Langues, Littératures et Cultures Étrangères',
    level: 'both' as const,
    sort_order: 7,
  },
  {
    name: 'HLP',
    slug: 'hlp',
    category: 'specialite' as const,
    icon: '📚',
    color: '#78716C',
    description: 'Humanités, Littérature et Philosophie',
    level: 'both' as const,
    sort_order: 8,
  },
  {
    name: 'Sciences de l\'Ingénieur',
    slug: 'sciences-ingenieur',
    category: 'specialite' as const,
    icon: '⚙️',
    color: '#64748B',
    description: 'Annales et exercices corrigés de SI',
    level: 'both' as const,
    sort_order: 9,
  },
  // Tronc commun
  {
    name: 'Français',
    slug: 'francais',
    category: 'tronc_commun' as const,
    icon: '✍️',
    color: '#7C3AED',
    description: 'Épreuves anticipées de Français (écrit + oral)',
    level: 'premiere' as const,
    sort_order: 10,
  },
  {
    name: 'Philosophie',
    slug: 'philosophie',
    category: 'tronc_commun' as const,
    icon: '🤔',
    color: '#B45309',
    description: 'Annales et sujets corrigés de Philo',
    level: 'terminale' as const,
    sort_order: 11,
  },
  {
    name: 'Histoire-Géographie',
    slug: 'histoire-geographie',
    category: 'tronc_commun' as const,
    icon: '🗺️',
    color: '#DC2626',
    description: 'Tronc commun Histoire-Géographie',
    level: 'both' as const,
    sort_order: 12,
  },
  {
    name: 'Enseignement Scientifique',
    slug: 'enseignement-scientifique',
    category: 'tronc_commun' as const,
    icon: '🔬',
    color: '#059669',
    description: 'Enseignement Scientifique tronc commun',
    level: 'both' as const,
    sort_order: 13,
  },
  {
    name: 'Anglais',
    slug: 'anglais',
    category: 'tronc_commun' as const,
    icon: '🗣️',
    color: '#2563EB',
    description: 'Épreuves d\'anglais tronc commun',
    level: 'both' as const,
    sort_order: 14,
  },
  {
    name: 'Grand Oral',
    slug: 'grand-oral',
    category: 'tronc_commun' as const,
    icon: '🎤',
    color: '#D97706',
    description: 'Préparation au Grand Oral du Bac',
    level: 'terminale' as const,
    sort_order: 15,
  },
]
